CREATE TABLE motor_ferret_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date1 DATE NOT NULL,
    date2 DATE,
    organizer TEXT NOT NULL,
    website TEXT NOT NULL,
    event_description TEXT,
    photo TEXT,
    address TEXT NOT NULL,
    address2 TEXT,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
